# Generated by Django 5.1.6 on 2025-02-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
