# Generated by Django 5.1.6 on 2025-02-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_bot_app', '0006_course_course_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_Content',
            new_name='CourseContent',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
